name: widget_component_annotation
description: "annotations for widget component library to enhance and creating boilerplate codes for BlocBuilder"
version: 1.0.3
homepage: https://github.com/vhdrjb/widget_component

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

