targets:
  $default:
    builders:
      widget_component|widget_component:
        enabled: true

builders:
  componentBuilder:
    target: ":widget_component_generator"
    import: "package:widget_component/builders.dart"
    builder_factories: ["widgetComponentBuilder"]
    build_extensions: { ".dart": [".component.g.part"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

