name: widget_component
description: "library to generate enhanced BlocBuilders or BLoC, Handle UI states easier, Reducing boilerplate codes"
version: 1.0.0
homepage: https://github.com/vhdrjb/widget_component/
repository: https://github.com/vhdrjb/widget_component/tree/main/widget_component

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.5.0
  build:  ^2.4.1
  analyzer: ^6.7.0
  widget_component_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13